# Generated by Django 4.2.29 on 2026-04-05 05:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('friesian', 'Friesian'), ('jersey', 'Jersey'), ('ayrshire', 'Ayrshire'), ('guernsey', 'Guernsey'), ('holstein', 'Holstein'), ('crossbreed', 'Crossbreed'), ('boran', 'Boran'), ('zebu', 'Zebu'), ('other', 'Other')], max_length=50)),
                ('color', models.CharField(choices=[('black_white', 'Black & White'), ('brown', 'Brown'), ('fawn', 'Fawn'), ('red', 'Red'), ('white', 'White'), ('mixed', 'Mixed')], default='black_white', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('lactating', 'Lactating'), ('dry', 'Dry'), ('pregnant', 'Pregnant'), ('heifer', 'Heifer'), ('bull', 'Bull'), ('sick', 'Sick'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='heifer', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cow_photos/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='farm_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_condition_score', models.DecimalField(blank=True, decimal_places=1, help_text='Score 1-5', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='cows.cow')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SMSReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('insemination', 'Insemination Due'), ('delivery', 'Expected Delivery'), ('vaccination', 'Vaccination Due'), ('health_check', 'Health Check Due'), ('dry_off', 'Dry Off Due'), ('custom', 'Custom')], max_length=20)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='cows.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='cows.farm')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('litres_sold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('payment_received', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_sales', to='cows.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insemination_date', models.DateField()),
                ('method', models.CharField(choices=[('ai', 'Artificial Insemination'), ('natural', 'Natural Mating'), ('embryo', 'Embryo Transfer')], default='ai', max_length=20)),
                ('bull_breed', models.CharField(blank=True, max_length=100)),
                ('semen_batch', models.CharField(blank=True, max_length=100)),
                ('technician', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_successful', models.BooleanField(default=False)),
                ('confirmed_pregnancy_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='cows.cow')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('checkup', 'Routine Checkup'), ('deworming', 'Deworming'), ('surgery', 'Surgery'), ('other', 'Other')], max_length=20)),
                ('diagnosis', models.CharField(blank=True, max_length=300)),
                ('treatment', models.TextField(blank=True)),
                ('medicine', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('vet_name', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('is_recovered', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cows.cow')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('feed_type', models.CharField(choices=[('hay', 'Hay'), ('silage', 'Silage'), ('concentrates', 'Concentrates'), ('mineral_lick', 'Mineral Lick'), ('pasture', 'Pasture'), ('napier', 'Napier Grass'), ('dairy_meal', 'Dairy Meal'), ('other', 'Other')], max_length=30)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='cows.cow')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='cows.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('feed', 'Feed & Fodder'), ('veterinary', 'Veterinary'), ('medicine', 'Medicine'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('insemination', 'Insemination'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cows.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='cow',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='cows.farm'),
        ),
        migrations.AddField(
            model_name='cow',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calves', to='cows.cow'),
        ),
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField()),
                ('calf_tag', models.CharField(blank=True, max_length=50)),
                ('calf_name', models.CharField(blank=True, max_length=100)),
                ('calf_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('calf_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calving_ease', models.CharField(choices=[('easy', 'Easy'), ('assisted', 'Assisted'), ('difficult', 'Difficult'), ('caesarean', 'Caesarean')], default='easy', max_length=20)),
                ('calf_survived', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calvings', to='cows.cow')),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cows.insemination')),
            ],
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('morning_litres', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('midday_litres', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evening_litres', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('milk_quality', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('discarded', 'Discarded')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_productions', to='cows.cow')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cow', 'date')},
            },
        ),
    ]
