# Generated by Django 4.2.29 on 2026-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
